<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Noir.CSharp.Compiler</RootNamespace>
    <AssemblyName>Noir.CSharp.Compiler</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Noir.Mobile.Scripting/Noir.Mobile.Scripting.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />\n    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
  </ItemGroup>
</Project>
