<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android35.0</TargetFramework>
    <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
    <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>
    <RuntimeIdentifiers>android-arm64;android-x64</RuntimeIdentifiers>
    <OutputType>Library</OutputType>
    <RootNamespace>Noir.Game</RootNamespace>
    <AssemblyName>Noir.Game</AssemblyName>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1422;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Noir.Mobile.Scripting/Noir.Mobile.Scripting.csproj" />
  </ItemGroup>
</Project>
