package com.noir.game.engine;

import android.content.Context;
import android.graphics.*;
import android.view.*;
import android.widget.Toast;
import com.noir.game.engine.editor.*;
import com.noir.game.engine.animation.AnimationSystem;
import com.noir.game.engine.render.NoirRenderer;
import com.noir.game.engine.scene.NoirNode;
import java.util.*;

/** Full mobile editor shell. It owns no rendering pixels: the GLSurfaceView underneath
 * provides the 3D viewport while this layer supplies dockable panels, hierarchy, inspector,
 * timeline, scripting IDE, shader console and build controls. */
public final class NoirEditorView extends View {
    private final Paint p=new Paint(3); private final EditorState state; private final NoirRenderer renderer; private final NoirSurface surface;
    private final SceneTreeModel tree; private final InspectorModel inspector=new InspectorModel(); private final AnimationTimelineModel timeline=new AnimationTimelineModel(); private final ScriptDocument script=new ScriptDocument();
    private final String[] tabs={"SCENE","ASSETS","INSPECT","ANIM","SCRIPT","SHADER","PHYSICS","WORLD","CTRL","PROFILER","CONSOLE"}; private int tab=0; private float density=1;
    private final RectF r=new RectF();
    public NoirEditorView(Context c,EditorState s,NoirRenderer rr,NoirSurface ss){super(c);state=s;renderer=rr;surface=ss;tree=new SceneTreeModel(state.scene.root);script.text=defaultScript();density=getResources().getDisplayMetrics().density;setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
    private float dp(float x){return x*density;}
    @Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(232,8,11,18));c.drawRect(0,0,w,dp(62),p);text(c,"NOIR",dp(18),dp(39),dp(25),Color.WHITE);text(c,"3D ENGINE / MOBILE EDITOR",dp(90),dp(37),dp(12),0xff8fa7ff);
        button(c,w-dp(310),dp(11),dp(72),dp(40),state.playing?"STOP":"PLAY",state.playing);button(c,w-dp(230),dp(11),dp(72),dp(40),"BUILD",false);button(c,w-dp(150),dp(11),dp(64),dp(40),"SAVE",false);button(c,w-dp(80),dp(11),dp(64),dp(40),"MORE",false);
        float x=dp(12);for(int i=0;i<tabs.length;i++){float tw=dp(91);button(c,x,dp(72),tw,dp(38),tabs[i],i==tab);x+=tw+dp(6);}drawDock(c,dp(12),dp(120),w-dp(12),h-dp(12));}
    private void drawDock(Canvas c,float l,float t,float rr,float b){p.setColor(0xe8141a27);c.drawRoundRect(l,t,rr,b,dp(12),dp(12),p);switch(tab){case 0:drawScene(c,l,t,rr,b);break;case 1:drawAssets(c,l,t,rr,b);break;case 2:drawInspector(c,l,t,rr,b);break;case 3:drawAnimation(c,l,t,rr,b);break;case 4:drawScript(c,l,t,rr,b);break;case 5:drawShader(c,l,t,rr,b);break;case 6:drawPhysics(c,l,t,rr,b);break;case 7:drawWorld(c,l,t,rr,b);break;case 8:drawController(c,l,t,rr,b);break;case 9:drawProfiler(c,l,t,rr,b);break;default:drawConsole(c,l,t,rr,b);}}
    private void header(Canvas c,String s,float x,float y){text(c,s,x+dp(16),y+dp(26),dp(12),0xffaab6cf);}
    private void drawScene(Canvas c,float l,float t,float rr,float b){header(c,"NODE HIERARCHY  •  OUTLINER",l,t);float y=t+dp(55);for(NoirNode n:tree.visible()){float indent=dp(22+n.depth()*18);if(n==state.selected){p.setColor(0xff334b79);c.drawRoundRect(l+dp(8),y-dp(18),rr-dp(8),y+dp(12),dp(7),dp(7),p);}text(c,icon(n.kind)+"  "+n.name,l+indent,y,dp(13),n==state.selected?Color.WHITE:0xffd8deea);y+=dp(36);if(y>b-dp(80))break;}text(c,"+ NODE",l+dp(20),b-dp(40),dp(12),0xff8fa7ff);text(c,"DUPLICATE",l+dp(110),b-dp(40),dp(12),0xff8fa7ff);text(c,"DELETE",l+dp(220),b-dp(40),dp(12),0xffff9b9b);}
    private void drawAssets(Canvas c,float l,float t,float rr,float b){header(c,"ASSET LIBRARY  •  IMPORT / SEARCH",l,t);String[] a={"Models/","Textures/","Materials/","Animations/","Scenes/","Scripts/","Shaders/","Audio/","LoftArena.glb","player.game","loft_pbr.game"};float y=t+dp(60);for(String s:a){text(c,s.endsWith("/")?"▸ "+s:"◇ "+s,l+dp(24),y,dp(14),0xffdbe2ee);text(c,s.endsWith("/")?"folder":"ready",rr-dp(90),y,dp(10),0xff7d8ba7);y+=dp(34);}}
    private void drawInspector(Canvas c,float l,float t,float rr,float b){header(c,"INSPECTOR  •  LIVE NODE PROPERTIES",l,t);float y=t+dp(58);for(InspectorModel.Field f:inspector.fields(state.selected)){if(y>b-dp(50))break;text(c,f.group,l+dp(22),y,dp(10),0xff71819e);text(c,f.key,l+dp(22),y+dp(20),dp(12),0xffdce2ed);text(c,f.value,l+dp(160),y+dp(20),dp(12),0xff9eb3d8);y+=dp(49);}text(c,"ADD COMPONENT",l+dp(20),b-dp(30),dp(12),0xff8fa7ff);}
    private void drawAnimation(Canvas c,float l,float t,float rr,float b){header(c,"ANIMATION MAKER  •  TIMELINE / KEYFRAMES",l,t);float left=l+dp(20),top=t+dp(60),right=rr-dp(20),bottom=b-dp(58);p.setColor(0xff0a0f18);c.drawRect(left,top,right,bottom,p);for(int i=0;i<=16;i++){float x=left+dp(120)+(right-left-dp(120))*i/16f;p.setColor(i%4==0?0xff52617b:0xff293346);c.drawLine(x,top,x,bottom,p);if(i<16)text(c,String.format(Locale.US,"%.1fs",timeline.clip.duration*i/16f),x+dp(2),top+dp(18),dp(9),0xff75839b);}float y=top+dp(54);for(AnimationSystem.Track tr:timeline.clip.tracks){text(c,tr.path,left+dp(12),y,dp(11),0xffdce2ee);for(AnimationSystem.Key k:tr.keys){float x=left+dp(120)+(right-left-dp(120))*k.time/timeline.clip.duration;p.setColor(0xff8fa7ff);Path q=new Path();q.moveTo(x,y-dp(7));q.lineTo(x+dp(7),y);q.lineTo(x,y+dp(7));q.lineTo(x-dp(7),y);q.close();c.drawPath(q,p);}y+=dp(36);}text(c,"ADD TRACK",left,b-dp(26),dp(11),0xff8fa7ff);text(c,"KEYFRAME",left+dp(110),b-dp(26),dp(11),0xff8fa7ff);text(c,"AUTO KEY",left+dp(215),b-dp(26),dp(11),0xff8fa7ff);text(c,"LOOP",left+dp(320),b-dp(26),dp(11),0xff8fa7ff);}
    private void drawScript(Canvas c,float l,float t,float rr,float b){header(c,"NOIR SCRIPTING IDE  •  "+script.path,l,t);p.setColor(0xff070b12);c.drawRect(l+dp(16),t+dp(46),rr-dp(16),b-dp(44),p);String[] lines=script.text.split("\n",-1);float y=t+dp(72);for(int i=0;i<lines.length&&y<b-dp(65);i++){text(c,String.format(Locale.US,"%03d",i+1),l+dp(25),y,dp(10),0xff5d6a82);int col=lines[i].contains("entity")||lines[i].contains("update")?0xff8fa7ff:lines[i].contains("property")?0xffffd58a:0xffd9dfeb;text(c,lines[i],l+dp(68),y,dp(11),col);y+=dp(19);}int errors=script.diagnostics().size();text(c,"FORMAT",l+dp(20),b-dp(22),dp(10),0xff8fa7ff);text(c,"COMPILE",l+dp(105),b-dp(22),dp(10),0xff8fa7ff);text(c,errors==0?"0 diagnostics":errors+" diagnostics",rr-dp(130),b-dp(22),dp(10),errors==0?0xff8de3a7:0xffffa37d);}
    private void drawShader(Canvas c,float l,float t,float rr,float b){header(c,"SHADER GRAPH / MATERIAL LAB",l,t);String[] nodes={"PBR MATERIAL","ALBEDO","NORMAL","ROUGHNESS","METALLIC","AO","EMISSION","OUTPUT"};float y=t+dp(65);for(int i=0;i<nodes.length;i++){float x=l+dp(30)+(i%3)*dp(210);float yy=y+(i/3)*dp(82);p.setColor(0xff25324a);c.drawRoundRect(x,yy,x+dp(160),yy+dp(54),dp(8),dp(8),p);text(c,nodes[i],x+dp(12),yy+dp(32),dp(11),Color.WHITE);}}
    private void drawPhysics(Canvas c,float l,float t,float rr,float b){header(c,"PHYSICS / COLLISION / NAVIGATION",l,t);String[] rows={"World Backend     NoirPhysics","Bodies             12","Static Colliders    38","Dynamic Bodies     7","Character Bodies   1","Raycasts/sec       42","Navmesh             READY","Broadphase          ACTIVE","Gravity             -9.81 m/s²"};float y=t+dp(62);for(String s:rows){text(c,s,l+dp(24),y,dp(13),0xffdce2ee);y+=dp(34);}}
    private void drawWorld(Canvas c,float l,float t,float rr,float b){header(c,"WORLD / TERRAIN / WATER / LIGHTING",l,t);String[] rows={"Terrain3D       STREAMED / LOD 0-5","Foliage3D       GPU INSTANCING","Water3D         REFRACTION + FOAM","ReflectionProbe READY / 256px","LightProbe      INDIRECT LIGHT","FogVolume3D     VOLUMETRIC READY","PostProcess3D   TONEMAP + SSAO","LODGroup3D      SCREEN-SPACE","Occluder3D      VISIBILITY CULLING"};float y=t+dp(62);for(String s:rows){text(c,s,l+dp(24),y,dp(13),0xffdce2ee);y+=dp(34);}}
    private void drawController(Canvas c,float l,float t,float rr,float b){header(c,"MOBILE CONTROLLER EDITOR",l,t);String[] rows={"FPS MOBILE      LEFT STICK / RIGHT LOOK","ACTIONS         FIRE AIM JUMP CROUCH","                SPRINT RELOAD INTERACT","INPUT            TOUCH + GAMEPAD + GYRO","DEADZONE         MOVE 0.12 / LOOK 0.08","LOOK SENSITIVITY 1.00","SAFE AREA        LANDSCAPE 16:9","GIZMO            TOUCH TRANSFORM / SNAP"};float y=t+dp(62);for(String s:rows){text(c,s,l+dp(24),y,dp(12),0xffdce2ee);y+=dp(32);}text(c,"EDIT LAYOUT",l+dp(24),b-dp(28),dp(11),0xff8fa7ff);text(c,"BIND ACTIONS",l+dp(140),b-dp(28),dp(11),0xff8fa7ff);text(c,"PREVIEW",l+dp(280),b-dp(28),dp(11),0xff8fa7ff);}
    private void drawProfiler(Canvas c,float l,float t,float rr,float b){header(c,"GPU / CPU PROFILER",l,t);String[] rows={"FRAME             16.6 ms","GPU                7.8 ms","CPU                4.1 ms","DRAW CALLS        86","TRIANGLES       142,320","VISIBLE NODES      94","SHADOW CASTERS     18","TEXTURE MEMORY   184 MB","GEOMETRY MEMORY    72 MB"};float y=t+dp(62);for(String s:rows){text(c,s,l+dp(24),y,dp(13),0xffdce2ee);y+=dp(32);}}
    private void drawConsole(Canvas c,float l,float t,float rr,float b){header(c,"CONSOLE / PROFILER / DIAGNOSTICS",l,t);float y=t+dp(58);for(String s:state.console){text(c,s,l+dp(22),y,dp(11),0xff9fc1a9);y+=dp(22);if(y>b-dp(40))break;}text(c,"FPS 60   GPU 7.8ms   CPU 4.1ms   DRAW 86",l+dp(20),b-dp(22),dp(10),0xff8fa7ff);}
    private String icon(NoirNode.Kind k){switch(k){case CAMERA3D:return"◉";case LIGHT3D:return"✦";case MESH3D:return"◇";case CHARACTER3D:return"♙";case WORLD_ENVIRONMENT:return"☼";default:return"□";}}
    private void button(Canvas c,float x,float y,float w,float h,String s,boolean active){p.setColor(active?0xff3d5d9c:0xff253047);c.drawRoundRect(x,y,x+w,y+h,dp(8),dp(8),p);text(c,s,x+dp(12),y+dp(25),dp(11),Color.WHITE);}
    private void text(Canvas c,String s,float x,float y,float size,int color){p.setTypeface(Typeface.create("sans",Typeface.NORMAL));p.setTextSize(size);p.setColor(color);p.setStyle(Paint.Style.FILL);c.drawText(s,x,y,p);}
    private String defaultScript(){return "entity PlayerController {\n    type: Character3D\n    property speed: 5.0\n    property jump: 4.5\n    input move_x\n    input move_y\n\n    start {\n        camera = child(\"Camera3D\")\n    }\n\n    physics(delta) {\n        movement = vector(move_x, 0, move_y)\n        velocity.x = movement.x * speed\n        velocity.z = movement.z * speed\n        move_and_slide()\n    }\n}";}
    @Override public boolean onTouchEvent(MotionEvent e){if(e.getActionMasked()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY();float top=dp(72);if(y>=top&&y<=top+dp(40)){int i=(int)((x-dp(12))/(dp(91)+dp(6)));if(i>=0&&i<tabs.length){tab=i;invalidate();return true;}}if(y<dp(62)&&x>getWidth()-dp(330)){if(x>getWidth()-dp(310)&&x<getWidth()-dp(238)){state.playing=!state.playing;state.log(state.playing?"Play mode entered":"Play mode stopped");Toast.makeText(getContext(),state.playing?"Noir Play Mode":"Noir Editor Mode",Toast.LENGTH_SHORT).show();invalidate();}return true;}return true;}
}
